eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
server:
  port: 8200

version: v1.0

# 给服务定义别名，让Eureka上可以订阅查询
spring:
  application:
    name: SEARCH
  cloud:
    stream:
      bindings:
        stream:                # 队列名称
          group: stream
        # 实现手动ACK
      rabbit:
        bindings:
          myMessage:
            consumer:
              acknowledgeMode: MANUAL
  rabbitmq:
    port: 5672
    username: admin
    password: admin
    virtual-host: admin
    host: 192.168.194.137
